services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: deltachat_server
    hostname: mail
    domainname: ${MY_DOMAIN}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=
      - ONE_DIR=1
      - SPOOF_PROTECTION=1
      - REPORT_RECIPIENT=0
    restart: always

networks:
  default:
    name: deltachat_network
